import { WallpaperItem } from '@/domain';

export const danielle: WallpaperItem[] = [
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/1/1b/NewJeans_Danielle_New_Jeans_concept_photo_%284%29.png/revision/latest/scale-to-width-down/1000?cb=20220722145645',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/0/01/NewJeans_Danielle_New_Jeans_concept_photo_%285%29.png/revision/latest/scale-to-width-down/1000?cb=20220722145703',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/7/77/NewJeans_Danielle_New_Jeans_concept_photo_%286%29.png/revision/latest/scale-to-width-down/1000?cb=20220828054604',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/4/42/NewJeans_Danielle_OMG_concept_photo_%281%29.png/revision/latest?cb=20230116012748',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/3/39/NewJeans_Danielle_Zero_promotional_photo.png/revision/latest/scale-to-width-down/1000?cb=20230518064831',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/d/d0/NewJeans_Danielle_Super_Shy_concept_photo_2.png/revision/latest?cb=20230707051523',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/4/44/NewJeans_Danielle_How_Sweet_concept_photo_1.png/revision/latest/scale-to-width-down/1000?cb=20240426043025',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/9/9a/NewJeans_Danielle_How_Sweet_concept_photo_4.png/revision/latest/scale-to-width-down/1000?cb=20240426043009',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/b/b1/NewJeans_Danielle_How_Sweet_concept_photo_5.png/revision/latest/scale-to-width-down/1000?cb=20240426042953',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/6/61/NewJeans_Danielle_How_Sweet_concept_photo_9.png/revision/latest/scale-to-width-down/1000?cb=20240524095711',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/e/e6/NewJeans_Danielle_How_Sweet_concept_photo_10.png/revision/latest?cb=20240524233304',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/0/06/NewJeans_Danielle_How_Sweet_concept_photo_11.png/revision/latest?cb=20240524233316',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/e/ec/NewJeans_Danielle_Supernatural_concept_photo_2.png/revision/latest/scale-to-width-down/1000?cb=20240510053150',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/d/db/NewJeans_Danielle_Supernatural_concept_photo_5.png/revision/latest/scale-to-width-down/1000?cb=20240510053145',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/2/28/NewJeans_Danielle_Supernatural_concept_photo_6.png/revision/latest/scale-to-width-down/1000?cb=20240510053132',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/6/67/NewJeans_Danielle_Supernatural_concept_photo_7.png/revision/latest/scale-to-width-down/1000?cb=20240510154303',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/e/e8/NewJeans_Danielle_Supernatural_concept_photo_9.png/revision/latest/scale-to-width-down/1000?cb=20240621162342',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/9/92/NewJeans_Danielle_Supernatural_concept_photo_10.png/revision/latest/scale-to-width-down/1000?cb=20240621162341',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/1/16/NewJeans_Danielle_Supernatural_concept_photo_11.png/revision/latest/scale-to-width-down/1000?cb=20240620153232',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/d/d3/NewJeans_Danielle_Highsnobiety_%28May_2023%29.png/revision/latest/scale-to-width-down/1000?cb=20230527115512',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/d/d1/NewJeans_Danielle_Vogue_Korea_%28March_2023%29_%2811%29.png/revision/latest/scale-to-width-down/1000?cb=20230528013333',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/c/c2/NewJeans_Danielle_Vogue_Korea_x_YSL_Beauty_%28November_2023%29_%282%29.png/revision/latest?cb=20231203160036',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://static.wikia.nocookie.net/kpop/images/b/b2/NewJeans_Danielle_Vogue_Korea_x_YSL_Beauty_%28November_2023%29_%281%29.png/revision/latest/scale-to-width-down/1000?cb=20231203155957',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://i.pinimg.com/736x/20/0a/de/200adea2c63a6afc3ab6b2b63b7eb397.jpg',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://i.pinimg.com/736x/a5/5e/d5/a55ed557e7e9511dce0ef6fd2b30bdb2.jpg',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://i.pinimg.com/736x/22/85/95/2285957107dee8bf7964e77fa839f126.jpg',
    category: 'Danielle',
    star: false,
  },
  {
    name: 'Danielle',
    link: 'https://i.pinimg.com/736x/6d/65/29/6d6529d4ca1eabf7ab5b9a943c653309.jpg',
    category: 'Danielle',
    star: false,
  },
];
